const opcodes = {
  lt: { minGas: 3, takes: 2, returns: 1 },
  gt: { minGas: 3, takes: 2, returns: 1 },
  slt: { minGas: 3, takes: 2, returns: 1 },
  sgt: { minGas: 3, takes: 2, returns: 1 },
  eq: { minGas: 3, takes: 2, returns: 1 },
  iszero: { minGas: 3, takes: 1, returns: 1 },
  and: { minGas: 3, takes: 2, returns: 1 },
  origin: { minGas: 2, takes: 0, returns: 1 },
  or: { minGas: 3, takes: 2, returns: 1 },
  xor: { minGas: 3, takes: 2, returns: 1 },
  not: { minGas: 3, takes: 1, returns: 1 },
  sha3: { minGas: 30, takes: 2, returns: 1 }, // TODO: incorrect
  address: { minGas: 2, takes: 0, returns: 1 },
  balance: { minGas: 100, takes: 1, returns: 1 },
  caller: { minGas: 2, takes: 0, returns: 1 },
  callvalue: { minGas: 2, takes: 0, returns: 1 },
  calldataload: { minGas: 3, takes: 1, returns: 1 },
  calldatasize: { minGas: 2, takes: 0, returns: 1 },
  calldatacopy: { minGas: 3, takes: 3, returns: 0 },
  codesize: { minGas: 2, takes: 0, returns: 1 },
  codecopy: { minGas: 3, takes: 3, returns: 0 },
  blockhash: { minGas: 20, takes: 1, returns: 1 },
  coinbase: { minGas: 2, takes: 0, returns: 1 },
  timestamp: { minGas: 2, takes: 0, returns: 1 },
  number: { minGas: 2, takes: 0, returns: 1 },
  difficulty: { minGas: 2, takes: 0, returns: 1 },
  minGaslimit: { minGas: 2, takes: 0, returns: 1 },
  chainid: { minGas: 2, takes: 0, returns: 1 },
  selfbalance: { minGas: 5, takes: 0, returns: 1 },
  pop: { minGas: 2, takes: 1, returns: 0 },
  mload: { minGas: 3, takes: 1, returns: 1 },
  mstore8: { minGas: 3, takes: 2, returns: 0 },
  mstore: { minGas: 3, takes: 2, returns: 0 },
  sload: { minGas: 2100, takes: 1, returns: 1 }, // TODO
  sstore: { minGas: 20000, takes: 1, returns: 0 }, // TODO
  jumpdest: { minGas: 1, takes: 0, returns: 0 },
  jumpi: { minGas: 10, takes: 2, returns: 0 },
  jump: { minGas: 8, takes: 1, returns: 0 },
  pc: { minGas: 2, takes: 0, returns: 1 },
  msize: { minGas: 2, takes: 0, returns: 1 },
  stop: { minGas: 0, takes: 0, returns: 0 },
  addmod: { minGas: 8, takes: 3, returns: 1 },
  add: { minGas: 3, takes: 2, returns: 1 },
  mulmod: { minGas: 8, takes: 3, returns: 1 },
  mul: { minGas: 5, takes: 2, returns: 1 },
  sub: { minGas: 3, takes: 2, returns: 1 },
  div: { minGas: 5, takes: 2, returns: 1 },
  sdiv: { minGas: 5, takes: 2, returns: 1 },
  mod: { minGas: 5, takes: 2, returns: 1 },
  smod: { minGas: 5, takes: 2, returns: 1 },
  exp: { minGas: 10, takes: 2, returns: 1 },
  signextend: { minGas: 50, takes: 2, returns: 1 },
  byte: { minGas: 3, takes: 2, returns: 1 },
  shl: { minGas: 3, takes: 2, returns: 1 },
  shr: { minGas: 3, takes: 2, returns: 1 },
  sar: { minGas: 3, takes: 2, returns: 1 },
  minGasprice: { minGas: 2, takes: 0, returns: 1 },
  extcodesize: { minGas: 100, takes: 1, returns: 1 },
  extcodecopy: { minGas: 100, takes: 4, returns: 0 }, // TODO
  returndatasize: { minGas: 2, takes: 0, returns: 1 },
  returndatacopy: { minGas: 3, takes: 3, returns: 0 }, //TODO
  extcodehash: { minGas: 100, takes: 1, returns: 0 }, // address
  minGas: { minGas: 2, takes: 0, returns: 1 },
  log0: { minGas: 375, takes: 2, returns: 0 },
  log1: { minGas: 750, takes: 3, returns: 0 },
  log2: { minGas: 1125, takes: 4, returns: 0 },
  log3: { minGas: 1500, takes: 5, returns: 0 },
  log4: { minGas: 1875, takes: 6, returns: 0 },
  create2: { minGas: 32000, takes: 4, returns: 1 },
  create: { minGas: 32000, takes: 3, returns: 1 },
  callcode: { minGas: 100, takes: 7, returns: 1 },
  call: { minGas: 100, takes: 7, returns: 1 },
  return: { minGas: 0, takes: 3, returns: 0 }, // TODO
  delegatecall: { minGas: 100, takes: 7, returns: 1 }, // TODO
  staticcall: { minGas: 100, takes: 7, returns: 1 }, // TODO
  revert: { minGas: 0, takes: 0, returns: 0 }, // TODO
  invalid: { minGas: NaN }, // TODO
  selfdestruct: { minGas: 5000, takes: 1 }, // TODO
  push32: { minGas: 3, takes: 0, returns: 1 },
  push31: { minGas: 3, takes: 0, returns: 1 },
  push30: { minGas: 3, takes: 0, returns: 1 },
  push29: { minGas: 3, takes: 0, returns: 1 },
  push28: { minGas: 3, takes: 0, returns: 1 },
  push27: { minGas: 3, takes: 0, returns: 1 },
  push26: { minGas: 3, takes: 0, returns: 1 },
  push25: { minGas: 3, takes: 0, returns: 1 },
  push24: { minGas: 3, takes: 0, returns: 1 },
  push23: { minGas: 3, takes: 0, returns: 1 },
  push22: { minGas: 3, takes: 0, returns: 1 },
  push21: { minGas: 3, takes: 0, returns: 1 },
  push20: { minGas: 3, takes: 0, returns: 1 },
  push19: { minGas: 3, takes: 0, returns: 1 },
  push18: { minGas: 3, takes: 0, returns: 1 },
  push17: { minGas: 3, takes: 0, returns: 1 },
  push16: { minGas: 3, takes: 0, returns: 1 },
  push15: { minGas: 3, takes: 0, returns: 1 },
  push14: { minGas: 3, takes: 0, returns: 1 },
  push13: { minGas: 3, takes: 0, returns: 1 },
  push12: { minGas: 3, takes: 0, returns: 1 },
  push11: { minGas: 3, takes: 0, returns: 1 },
  push10: { minGas: 3, takes: 0, returns: 1 },
  push9: { minGas: 3, takes: 0, returns: 1 },
  push8: { minGas: 3, takes: 0, returns: 1 },
  push7: { minGas: 3, takes: 0, returns: 1 },
  push6: { minGas: 3, takes: 0, returns: 1 },
  push5: { minGas: 3, takes: 0, returns: 1 },
  push4: { minGas: 3, takes: 0, returns: 1 },
  push3: { minGas: 3, takes: 0, returns: 1 },
  push2: { minGas: 3, takes: 0, returns: 1 },
  push1: { minGas: 3, takes: 0, returns: 1 },
  swap16: { minGas: 3, takes: 16, returns: 16 },
  swap15: { minGas: 3, takes: 15, returns: 15 },
  swap14: { minGas: 3, takes: 14, returns: 14 },
  swap13: { minGas: 3, takes: 13, returns: 13 },
  swap12: { minGas: 3, takes: 12, returns: 12 },
  swap11: { minGas: 3, takes: 11, returns: 11 },
  swap10: { minGas: 3, takes: 10, returns: 10 },
  swap9: { minGas: 3, takes: 9, returns: 9 },
  swap8: { minGas: 3, takes: 8, returns: 8 },
  swap7: { minGas: 3, takes: 7, returns: 7 },
  swap6: { minGas: 3, takes: 6, returns: 6 },
  swap5: { minGas: 3, takes: 5, returns: 5 },
  swap4: { minGas: 3, takes: 4, returns: 4 },
  swap3: { minGas: 3, takes: 3, returns: 3 },
  swap2: { minGas: 3, takes: 2, returns: 2 },
  swap1: { minGas: 3, takes: 1, returns: 1 },
  dup16: { minGas: 3, takes: 16, returns: 17 },
  dup15: { minGas: 3, takes: 15, returns: 16 },
  dup14: { minGas: 3, takes: 14, returns: 15 },
  dup13: { minGas: 3, takes: 13, returns: 14 },
  dup12: { minGas: 3, takes: 12, returns: 13 },
  dup11: { minGas: 3, takes: 11, returns: 12 },
  dup10: { minGas: 3, takes: 10, returns: 11 },
  dup9: { minGas: 3, takes: 9, returns: 10 },
  dup8: { minGas: 3, takes: 8, returns: 9 },
  dup7: { minGas: 3, takes: 7, returns: 8 },
  dup6: { minGas: 3, takes: 6, returns: 7 },
  dup5: { minGas: 3, takes: 5, returns: 6 },
  dup4: { minGas: 3, takes: 4, returns: 5 },
  dup3: { minGas: 3, takes: 3, returns: 4 },
  dup2: { minGas: 3, takes: 2, returns: 3 },
  dup1: { minGas: 3, takes: 1, returns: 2 },
};

module.exports = {
  opcodes,
};
